# Configuration for move-issues app - https://probot.github.io/apps/move/

# Delete the command comment. Ignored when the comment also contains other content
deleteCommand: true
# Close the source issue after moving
closeSourceIssue: true
# Lock the source issue after moving
lockSourceIssue: false
# Set custom aliases for targets
 aliases:
   main: bpkg/bpkg

#EOF
